export type UserRole = 'owner' | 'finance_manager' | 'inventory_head' | 'hr_admin' | 'support_agent';

export interface Business {
  id: string;
  name: string;
  gstin: string;
  currency: string;
  plan: string;
  createdDate: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar: string;
}

// 1. Finance Types
export interface InvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  customerName: string;
  customerId: string;
  date: string;
  dueDate: string;
  items: InvoiceItem[];
  subtotal: number;
  gstAmount: number; // 18% GST
  total: number;
  status: 'paid' | 'pending' | 'overdue';
  autoGenerated: boolean;
}

export interface Expense {
  id: string;
  category: 'Raw Materials' | 'Salaries' | 'Utilities' | 'Marketing' | 'Logistics' | 'Software' | 'Rent';
  amount: number;
  vendor: string;
  date: string;
  status: 'approved' | 'pending';
  receiptUrl?: string;
}

export interface CashFlowDataPoint {
  month: string;
  inflow: number;
  outflow: number;
  netCash: number;
  isProjected?: boolean;
}

// 2. Inventory Types
export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string;
  stockQuantity: number;
  reorderPoint: number;
  optimalOrderQty: number;
  unitPrice: number;
  costPrice: number;
  supplierId: string;
  stockoutRiskScore: number; // 0 - 100%
  forecastDemand30d: number;
}

export interface StockLedgerEntry {
  id: string;
  productId: string;
  productName: string;
  changeType: 'sale' | 'restock' | 'adjustment' | 'return';
  quantity: number;
  timestamp: string;
  performedBy: string;
}

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  phone: string;
  leadTimeDays: number;
  rating: number;
}

// 3. HR Types
export interface Employee {
  id: string;
  name: string;
  role: string;
  department: string;
  baseSalary: number;
  epfDeduction: number; // 12%
  esiDeduction: number; // 0.75%
  netSalary: number;
  status: 'active' | 'on_leave' | 'terminated';
  joinedDate: string;
}

export interface AttendanceRecord {
  id: string;
  empId: string;
  empName: string;
  date: string;
  checkIn: string;
  checkOut: string;
  status: 'present' | 'absent' | 'late' | 'half_day';
}

export interface PayrollRun {
  id: string;
  month: string;
  totalEmployees: number;
  totalGrossSalary: number;
  totalDeductions: number;
  totalNetSalary: number;
  status: 'draft' | 'processed' | 'disbursed';
  runDate: string;
}

// 4. Marketing Types
export interface Customer {
  id: string;
  name: string;
  company: string;
  email: string;
  phone: string;
  rfmSegment: 'Champions' | 'Loyal Customers' | 'At Risk' | 'Need Attention' | 'Lost';
  totalSpent: number;
  orderCount: number;
  lastPurchaseDaysAgo: number;
  churnRiskScore: number; // 0 - 100%
}

export interface Campaign {
  id: string;
  title: string;
  channel: 'Email' | 'WhatsApp' | 'SMS';
  targetSegment: string;
  copyText: string;
  status: 'draft' | 'scheduled' | 'sent';
  createdDate: string;
  estimatedReach: number;
}

// 5. Support Types
export interface SupportTicket {
  id: string;
  ticketNumber: string;
  customerName: string;
  customerEmail: string;
  subject: string;
  message: string;
  category: 'Order Status' | 'Billing' | 'Product Inquiry' | 'Returns' | 'Technical';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'open' | 'in_progress' | 'resolved';
  aiSuggestedReply?: string;
  sentiment: 'Positive' | 'Neutral' | 'Negative';
  createdDate: string;
}

export interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}

// 6. Business Analytics & Orchestrator Types
export interface EventLogItem {
  id: string;
  timestamp: string;
  agentSource: 'Finance' | 'Inventory' | 'HR' | 'Marketing' | 'Support' | 'Analytics' | 'Orchestrator';
  eventType: string;
  description: string;
  metadata?: Record<string, any>;
}

export interface AnomalyAlert {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  agentSource: 'Finance' | 'Inventory' | 'HR' | 'Marketing' | 'Support' | 'Analytics' | 'Orchestrator';
  title: string;
  message: string;
  recommendedAction: string;
  timestamp: string;
  status: 'open' | 'acknowledged' | 'resolved';
}

export interface SystemState {
  business: Business;
  currentUser: User;
  invoices: Invoice[];
  expenses: Expense[];
  cashFlowForecast: CashFlowDataPoint[];
  products: Product[];
  stockLedger: StockLedgerEntry[];
  suppliers: Supplier[];
  employees: Employee[];
  attendance: AttendanceRecord[];
  payrollRuns: PayrollRun[];
  customers: Customer[];
  campaigns: Campaign[];
  supportTickets: SupportTicket[];
  faqs: FAQItem[];
  eventLogs: EventLogItem[];
  anomalyAlerts: AnomalyAlert[];
}
