import { DataStore } from '../DataStore';
import { Invoice } from '../../../types';

export class InvoiceRepository {
  public static getAll(businessId?: string): Invoice[] {
    const invoices = DataStore.getState().invoices;
    if (!businessId) return invoices;
    return invoices.filter((inv: any) => inv.businessId === businessId || !inv.businessId);
  }

  public static create(invoiceData: Partial<Invoice>, businessId?: string): Invoice {
    const id = invoiceData.id || `INV-2026-${Math.floor(100 + Math.random() * 900)}`;
    const newInvoice: Invoice = {
      id,
      invoiceNumber: invoiceData.invoiceNumber || id,
      customerName: invoiceData.customerName || 'Client Corp',
      customerId: invoiceData.customerId || 'cust_001',
      date: invoiceData.date || new Date().toISOString().split('T')[0],
      dueDate: invoiceData.dueDate || new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
      items: invoiceData.items || [],
      subtotal: invoiceData.subtotal || 10000,
      gstAmount: invoiceData.gstAmount || 1800,
      total: invoiceData.total || 11800,
      status: invoiceData.status || 'pending',
      autoGenerated: Boolean(invoiceData.autoGenerated),
    };
    (newInvoice as any).businessId = businessId;

    DataStore.updateState((state) => ({
      ...state,
      invoices: [newInvoice, ...state.invoices],
    }));

    return newInvoice;
  }

  public static updateStatus(id: string, status: Invoice['status'], businessId?: string): Invoice {
    let updated: Invoice | undefined;

    DataStore.updateState((state) => {
      const updatedInvoices = state.invoices.map((inv: any) => {
        if ((inv.id === id || inv.invoiceNumber === id) && (!businessId || inv.businessId === businessId || !inv.businessId)) {
          updated = { ...inv, status };
          return updated;
        }
        return inv;
      });
      return { ...state, invoices: updatedInvoices };
    });

    if (!updated) {
      throw new Error(`Invoice ${id} not found.`);
    }

    return updated;
  }
}
